version: "3.9"
services:
  drawer:
    image: harryhsu4/detection-drawer:latest
    restart: always
    ports:
    - 1000:1000
    volumes:
    - ./config.js:/work/api/config.js
    environment:
    - RTSP_URL_1=rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
    - NX_URL_1=http://host.docker.internal:1002/api/drawer/1
    - NAME_1=TEST1
    - RTSP_URL_2=rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4
    - NX_URL_2=http://host.docker.internal:1002/api/drawer/2
    - NAME_2=TEST2
    entrypoint: "node app"
    extra_hosts:
    - "host.docker.internal:host-gateway"